name: MYCLI
on:
  push: 
    branches: 
      - main
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - run: |
          node -v
          echo ${{secrets.MYSECRET}}
          
  job2:
    runs-on: ubuntu-latest
    container:
      image: node:8
    steps:
      - run: |
          node -v
  
